name: Gating

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update repositories
        run: sudo apt-get -y update 

      - name: Install tools
        run: sudo apt-get -y install ninja-build meson gcc libplayerctl-dev

      - name: Create build folder
        run: meson setup build

      - name: Compile
        run: meson compile -C build

  format:
    name: Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update repositories
        run: sudo apt-get -y update 

      - name: Install tools
        run: sudo apt-get -y install ninja-build meson gcc libplayerctl-dev clang-format-20

      - name: Create build folder
        run: meson setup build

      - name: Format check
        run: ninja -C build clang-format-check

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update repositories
        run: sudo apt-get -y update 

      - name: Install tools
        run: sudo apt-get -y install ninja-build meson gcc libplayerctl-dev clang-tidy

      - name: Create build folder
        run: meson setup build

      - name: Lint
        run: cd build && clang-tidy ../main.cpp
